language: swift
osx_image: xcode11
before_install:
- set -o pipefail
- xcrun simctl boot "iPhone 8" || echo "(Pre)Launched the simulator."
script:
- pod lib lint --allow-warnings
- pod spec lint --allow-warnings